title: Jeffrey Shen's Blog
email: jeffreyshencc@gmail.com
description: "Politics, culture, and society—explored with data & CS."
baseurl: "/"
url: "http://blog.jeffreyshen.com"
twitter_username: JeffreyShen10
github_username:  jeffreyshen19

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed

# Ignore 
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - assets/src
