title: Jeffrey Shen
email: jeffreyshencc@gmail.com
description: "Politics, culture, and society—explored with data & CS."
baseurl: "/"
url: "http://blog.jeffreyshen.com"
twitter_username: JeffreyShen10
github_username:  jeffreyshen19

plugins:
  - jekyll-jsminify

# Build settings
theme: minima
markdown: kramdown
plugins:
  - jekyll-feed

# Ignore
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md
  - bower_components

# SCSS
sass:
    sass_dir: scss
    style: compressed
